name: Run Quotex Bot

on:
  schedule:
    - cron: '*/5 * * * *'  # This cron schedule runs the workflow every 5 minutes
  push:
    branches:
      - main  # Trigger on push to the main branch
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Specify the Python version you're using

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyrogram asyncio

      - name: Run Quotex Bot
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          USER_PHONE_NUMBER: ${{ secrets.USER_PHONE_NUMBER }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          PRIVATE_GROUP_ID: ${{ secrets.PRIVATE_GROUP_ID }}
        run: |
          python your_script.py
